---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-stage
  namespace: staging
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stage-*
spec:
  releaseName: stage
  chart:
    git: git@github.com:extremeFunk/k8s-echo.git
    path: k8/flux-config/charts/echo/
    ref: dev
  values:
    image:
      repository: us.gcr.io/echo-k8s-project/echo
      tag: latest
    replicaCount: 2
    hpa:
      enabled: false
    configMap:
      dbname: echo-stage
    ingress:
      hosts:
        - host: echo-stage.mooo.com
          paths: [/]
      tls:
        - hosts:
            - echo-stage.mooo.com
          secretName: stage-tls
      db:
        secretName: stage-echo
