---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-prod
  namespace: production
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: sever:~1.0
spec:
  releaseName: prod
  chart:
    git: git@github.com:extremeFunk/k8s-echo.git
    path: k8s-echo/k8/flux-config/charts/echo/
    ref: dev
  values:
    image:
      repository: us.gcr.io/echo-k8s-project/echo
      tag: latest
    replicaCount: 2
    hpa:
      enabled: false