---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-prod
  namespace: production
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: sever:~1.0
spec:
  releaseName: prod
  chart:
    git: git@github.com:extremeFunk/echo-pod-conf.git
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: us.gcr.io/echo-final-project/echo
      tag: v1.2
    replicaCount: 2
    hpa:
      enabled: false