apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "echo.fullname" . }}
data:
  PORT: "{{ .Values.configMap.port }}"
  LOGLEVEL: "{{ .Values.configMap.loglevel }}"
{{ if .Values.db.secretName }}
  PERSIST: "{{ .Values.configMap.persist }}"
{{- end }}
  DBNAME: "{{ .Values.configMap.dbname }}"
