---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: dev
  chart:
    git: git@github.com:extremeFunk/echo-pod-conf.git
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: us.gcr.io/rainrobot-k8-project/echo
      tag: latest
    replicaCount: 2
    hpa:
      enabled: false
    configMap:
      persist: false
    ingress:
      hosts:
        - host: echo-dev.mooo.com
          paths: [/]
      tls:
      - hosts:
        - echo-dev.mooo.com
        secretName: dev-tls
